import { AiFillStar } from "react-icons/ai";
import React from 'react';

const data = [
  {
    img: "/images/photo_6194831202075131782_x.jpg",
    title: "𝘤𝘶𝘴𝘵𝘰𝘮𝘪𝘻𝘦𝘥 𝘣𝘳𝘢𝘤𝘦𝘭𝘦𝘵",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "custom",
    company: "bracelet",
    color: "white",
    category: "sneakers",
  },
  {
    img: "/images/photo_6194831202075131791_x.jpg",
    title: "𝘺𝘪𝘯 𝘢𝘯𝘥 𝘺𝘢𝘯𝘨 𝘣𝘳𝘢𝘤𝘦𝘭𝘦𝘵",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "custom",
    company: "bracelet",
    color: "red",
    category: "sneakers",
  },

  {
    img: "/images/photo_6194831202075131781_x.jpg",
    title: "𝘴𝘵𝘢𝘳 𝘣𝘳𝘢𝘤𝘦𝘭𝘦𝘵 (𝘤𝘶𝘴𝘵𝘰𝘮)",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "custom",
    company: "bracelet",
    color: "green",
    category: "sneakers",
  },
  {
    img: "/images/photo_6194831202075131785_x.jpg",
    title: "𝘣𝘭𝘰𝘴𝘴𝘰𝘮",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "250",
    company: "necklace",
    color: "black",
    category: "sneakers",
  },
  {
    img: "/images/photo_6194831202075131786_x.jpg",
    title: "𝘺𝘪𝘯 𝘢𝘯𝘥 𝘺𝘢𝘯𝘨 4`4",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "240",
    company: "canvas",
    color: "green",
    category: "sandals",
  },
  {
    img: "/images/photo_6194831202075131771_x.jpg",
    title: "𝘢𝘻𝘶𝘳𝘦 𝘯𝘢𝘤𝘬𝘭𝘢𝘤𝘦",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳499",
    newPrice: "380",
    company: "necklace",
    color: "black",
    category: "sandals",
  },

  {
    img: "/images/photo_6194831202075131787_x.jpg",
    title: "𝘢𝘭𝘢𝘨 𝘢𝘢𝘴𝘮𝘢𝘢𝘯",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳599",
    newPrice: "270",
    company: "canvas",
    color: "white",
    category: "flats",
  },

  {
    img: "/images/photo_6194831202075131779_x.jpg",
    title: "𝘤𝘶𝘴𝘵𝘰𝘮𝘪𝘻𝘦𝘥 𝘣𝘳𝘢𝘤𝘦𝘭𝘦𝘵𝘴",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳299",
    newPrice: "custom",
    company: "bracelet",
    color: "green",
    category: "sneakers",
  },
  {
    img: "/images/photo_6194831202075131801_x.jpg",
    title: "𝘤𝘶𝘴𝘵𝘰𝘮𝘪𝘻𝘦𝘥 𝘣𝘳𝘢𝘤𝘦𝘭𝘦𝘵𝘴",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳299",
    newPrice: "custom",
    company: "bracelet",
    color: "green",
    category: "sneakers",
  },

  {
    img: "/images/photo_6194831202075131776_x.jpg",
    title: "𝘣𝘭𝘶𝘴𝘩 𝘯𝘦𝘤𝘬𝘭𝘢𝘤𝘦",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳299",
    newPrice: "custom",
    company: "necklace",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "/images/photo_6194831202075131792_x.jpg",
    title: "𝘤𝘭𝘢𝘳𝘢𝘮𝘢𝘺",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "210",
    company: "rings",
    color: "green",
    category: "sneakers",
  },
  {
    img: "/images/photo_6194831202075131773_x.jpg",
    title: "𝘢𝘴𝘵𝘳𝘢 ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳299",
    newPrice: "170",
    company: "rings",
    color: "red",
    category: "sneakers",
  },
  {
    img: "/images/photo_6194831202075131770_x.jpg",
    title: "𝘤𝘶𝘴𝘵𝘰𝘮𝘪𝘻𝘦𝘥 𝘳𝘪𝘯𝘨𝘴",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳199",
    newPrice: "70",
    company: "rings",
    color: "black",
    category: "sneakers",
  },
  {
    img: "/images/photo_6194831202075131769_x.jpg",
    title: "𝘤𝘶𝘴𝘵𝘰𝘮𝘪𝘻𝘦𝘥 𝘱𝘩𝘰𝘯𝘦 𝘤𝘩𝘢𝘳𝘮",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "350",
    company: "rings",
    color: "white",
    category: "sneakers",
  },

  {
    img: "/images/photo_6194831202075131778_x.jpg",
    title: "𝘣𝘦𝘢𝘥𝘦𝘥 𝘳𝘪𝘯𝘨𝘴",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳99",
    newPrice: "50 each",
    company: "rings",
    color: "green",
    category: "sneakers",
  },
  {
    img: "/images/photo_6194831202075131790_x.jpg",
    title: "𝘮𝘦𝘢𝘥𝘰𝘸 ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳350",
    newPrice: "230",
    company: "canvas",
    color: "red",
    category: "flats",
  },
  {
    img: "/images/photo_6194831202075131774_x.jpg",
    title: "𝘣𝘦𝘢𝘥𝘦𝘥 𝘣𝘳𝘢𝘤𝘦𝘭𝘦𝘵𝘴",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "90-180",
    company: "bracelet",
    color: "black",
    category: "flats",
  },
  {
    img: "/images/photo_6194831202075131775_x.jpg",
    title: "𝘤𝘶𝘴𝘵𝘰𝘮𝘪𝘻𝘦𝘥 𝘣𝘳𝘢𝘤𝘦𝘭𝘦𝘵𝘴 ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "custom",
    company: "bracelet",
    color: "red",
    category: "heels",
  },
  {
    img: "/images/photo_6194831202075131646_x.jpg",
    title: "𝘱𝘦𝘢𝘳𝘭 ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "140",
    company: "bracelet",
    color: "red",
    category: "sneakers",
  },

  {
    img: "/images/photo_6194831202075131780_x.jpg",
    title: "⭐ 𝘧𝘪𝘴𝘩 𝘣𝘳𝘢𝘤𝘦𝘭𝘦𝘵 ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳299",
    newPrice: "custom",
    company: "bracelet",
    color: "black",
    category: "heels",
  },
  {
    img: "/images/photo_6194831202075131772_x.jpg",
    title: "𝘴𝘵𝘦𝘭𝘭𝘢",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "290",
    company: "necklace",
    color: "black",
    category: "heels",
  },
  {
    img: "/images/photo_6194831202075131789_x.jpg",
    title: "𝘢𝘳𝘳𝘪𝘦𝘵𝘵𝘺",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳399",
    newPrice: "230",
    company: "necklace",
    color: "white",
    category: "heels",
  },
  {
    img: "/images/photo_6194831202075131788_x.jpg",
    title: "𝘮𝘦𝘢𝘥𝘰𝘸 𝘰𝘧 𝘨𝘳𝘢𝘤𝘦",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "৳499",
    newPrice: "300",
    company: "necklace",
    color: "black",
    category: "heels",
  },

];

export default data;

